### PR TITLE
Build dvc-task v0.1.0

### PR DESCRIPTION
**Pull request by maresb**
Checklist
* [X] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [X] Bumped the build number (if the version is unchanged)
* [X] Reset the build number to `0` (if the version changed)
* [X] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [X] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by maresb** [comment]
@conda-forge-admin, please rerender

**Comment by maresb** [comment]
### Please don't merge this into the `main` branch.

We just need to create a new branch called "v0.1.0", retarget this PR to that branch, merge, and then you'll get the desired build of v0.1.0.

**Comment by efiop** [comment]
Unfortunately, alpha versions are not avaialble in conda, hence why we released dvc-task 0.1.1 with slacker requirements 🙁 So looks like this is not going to work and we are better off just bumping the requirements in dvc (we probably just forgot to do it cc @pmrowla @karajan1001).

**Comment by maresb** [comment]
It's still possible to make alpha versions available on Conda-Forge, but one typically does that under a dev label. Thus the install command would become:
```
mamba install -c conda-forge -c conda-forge/label/kombu_dev dvc
```

**Comment by maresb** [comment]
The procedure is the same as what I suggested here (but targeting a new branch typically called `dev`), plus you need to create an additional `recipe/conda_build_config.yaml` file with the contents

```yaml
channel_targets:
  - conda-forge kombu_dev
```

And then in `dvc-feedstock` you'd need the same filename with contents

```yaml
channel_sources:
  - conda-forge/label/kombu_dev,conda-forge
```

**Comment by maresb** [comment]
And if you ran

```
mamba install -c conda-forge dvc
```

then the solver would install the latest `dvc` version which doesn't require an alpha version of kombu.

**Comment by efiop** [comment]
@maresb Makes sense! Thanks for researching this! 🙏 

Looks like we no longer need this change to release dvc conda package though. We'll release next dvc version with correct dvc-task requirements. Closing for now.

**Comment by maresb** [comment]
Great, glad I could help clarify things!

**Comment by pmrowla** [comment]
for reference, submitted upstream PR's to get the kombu/celery alpha's released on conda dev branches:

https://github.com/conda-forge/kombu-feedstock/pull/58
https://github.com/conda-forge/celery-feedstock/pull/71

**Pull request closed without merging**
